services:
  - type: web
    name: digipin-flask-app
    env: python
    pythonVersion: 3.11
    buildCommand: ""
    startCommand: python app.py
    plan: free
    branch: main
    region: oregon
