services:
  - type: web
    name: digipin-flask-app
    env: python
    pythonVersion: 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: free
    branch: main
    region: oregon
    envVars:
      - key: DATABASE_URL
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: INDIA_POST_API_KEY
        value: "your_india_post_api_key_here"
      - key: INDIA_POST_API_URL
        value: "https://dak.indiapost.gov.in/api/v1"
