services:
  - type: web
    name: digipin-integration
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: testdrive-db
          property: connectionString
